# TODO: create workflow to check pull requests
name: docs_pages_workflow

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:

  deploy_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Run entire workflow
        env:
          USE_SSH: true
          GIT_USER: vgucsd
        run: |
          # install required packages -- not sure if all are required
          sudo apt-get update
          sudo apt-get -y install python3-pip git
          pip3 install yapf pydoc-markdown
          ls
          # install csdl
          pip3 install -e .
          # install a back end (in this case, csdl_om)
          git clone --depth=1 https://lsdolab@github.com/lsdolab/csdl_om.git
          pip3 install -e csdl_om/
          here=`pwd`
          # generate markdown files containing API docs from docstrings
          echo ${here}
          pushd ${here}/csdl/utils/
          ./generate_api_docs.sh
          ls ../../docs/docs/developer/
          cat ../../docs/docs/lang_ref/model.mdx
          popd
          # generate markdown files containing worked examples
          python3 ${here}/csdl/utils/generate_worked_examples_mdx.py ${here}
          echo "Worked Examples:"
          ls ${here}/docs/docs/worked_examples
          pushd docs
          pwd
          ls
          # deploy docs
          git config --global user.email "vgandari@eng.ucsd.edu"
          git config --global user.name "vgucsd"
          if [ -e yarn.lock ]; then
            echo "yarn i RUNNING"
            yarn install --frozen-lockfile
          else
            echo "npm i RUNNING"
            npm i
          fi
          npm run deploy

  # checks:
  #   needs: setup_repo
  #   if: github.event_name != 'push'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '12.x'
  #     - uses: webfactory/ssh-agent@v0.5.0
  #       with:
  #         ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
  #     - name: Test Build
  #       run: |
  #         if [ -e yarn.lock ]; then
  #           yarn install --frozen-lockfile
  #         elif [ -e package-lock.json ]; then
  #           npm ci
  #         else
  #           npm i
  #         fi
  #         npm run build

  # gh-release:
  #   needs: setup_repo
  #   if: github.event_name != 'pull_request'
  #   runs-on: ubuntu-latest
